package:
  name: "dynamo-release"
  version: "1.3.1"

source:
#  git_rev: v1.3.1
#  git_url: https://github.com/aristoteleo/dynamo-release.git
  url: https://github.com/aristoteleo/dynamo-release/archive/refs/tags/v1.3.1.tar.gz
  sha256: 15c28aadeafada5bcce0619b527eccb679fba1d5e58551c29de6e06a0673c7a1

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
  host:
    - python
    - typing-extensions
    - openpyxl
    - get_version
    - numpy 1.23.*
    - markdown 3.3.*
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - numpy 1.23.*
    - markdown 3.3.*
    - pandas >=1.3.5
    - scipy >=1.4.1
    - scikit-learn >=0.19.1
    - anndata >=0.8.0
    - loompy >=3.0.5
    - matplotlib >=3.5.3
    - more-itertools
    - nxviz ==0.7.3
    - get_version >=3.5.4
    - numdifftools >=0.9.39
    - umap-learn >=0.5.1
    - PATSY
    - statsmodels
    - numba >=0.54.0
    - seaborn >=0.9.0
    - colorcet >=2.0.1
    - tqdm
    - python-igraph >=0.7.1
    - louvain ==0.8.0
    - pynndescent >=0.5.2
    - pre-commit
    - networkx
    - typing-extensions
    - openpyxl
    - session-info >=1.0.0

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - dynamo
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/aristoteleo/dynamo-release
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Inclusive model of expression dynamics with metabolic labeling based scRNA-seq / multiomics, vector field reconstruction, potential landscape mapping, differential geometry analyses, and most probably paths / in silico perturbation predictions."

extra:
  recipe-maintainers:
    - Xiaojieqiu